version: '3.8'

services:
  my-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "9006:9006"
    volumes:
      - ./src:/home
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb+srv://user:#hK*Gr4#XdEFhjd@cluster0.fuei3t3.mongodb.net/my-database?retryWrites=true&w=majority
