version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9006:9006"
    environment:
      SPRING_DATA_MONGODB_URI: "mongodb+srv://user:#hK*Gr4#XdEFhjd@cluster0.fuei3t3.mongodb.net/mydb?retryWrites=true&w=majority"
      SPRING_DATA_MONGODB_DATABASE: Edag
    depends_on:
      - mongo
  mongo:
    image:  mongo:4.4.6
    restart: always
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: #hK*Gr4#XdEFhjd

